# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: Code Coverage
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Tests and Code Coverage
      run: |
        pytest --cache-clear --cov=./ > pytest-coverage.txt,
        pytest --cov-report term-missing --cov=./
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 2c43afb51ab938eddf24e9f4c7f55d3f
        filename: test.json
        label: Hello
        message: World
        color: orange
