# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: Code Coverage
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
    # (Other steps go here)
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
